### PR TITLE
Use correct `ssize_t` type on MSVC

### PR DESCRIPTION
**Pull request by SamuelMarks**

### CODE REVIEW

**Comment by fredrikwidlund** [comment]
Would you like to request a change in https://github.com/h2o/picohttpparser instead? What system do you want use libreactor on?

**Comment by SamuelMarks** [comment]
I can try but they don't appear to be active (see their long active PRs).

Haven't decided yet. I'll probably end up adding CMake to libreactor and packaging it on:

- Windows
  - MinGW
  - Cygwin
  - MSVC
- DOS
  - OpenWatcom (for DOS)
- *BSD
  - FreeBSD
  - OpenBSD
- SunOS
  - Solaris
    - OpenSolaris
      - illumos
        - OpenIndiana
- macOS
- iOS
- Android
- Linux

---

That is; assuming I don't get distracted by other things and that you're interested!

**Comment by fredrikwidlund** [comment]
I'm afraid I'm leaving this version of libreactor behind in favour of [libreactorng](https://github.com/fredrikwidlund/libreactorng) (temporary name) that will replace it. It is completely built on io_uring and will be difficult to port...

**Comment by SamuelMarks** [comment]
Ouch; ok yeah that's very specific to Linux. No worries then; best of luck

**Pull request closed without merging**
